export interface Product {
  name: string;
  category: string;
  ageRange: string;
  emoji: string;
}

export const PRODUCTS: Product[] = [
  // ── Kids - Clothing ──────────────────────────────────────────────
  { name: "Newborn clothes", category: "Kids - Clothing", ageRange: "0-3mo", emoji: "👕" },
  { name: "0-3mo clothes", category: "Kids - Clothing", ageRange: "0-3mo", emoji: "👕" },
  { name: "3-6mo clothes", category: "Kids - Clothing", ageRange: "3-6mo", emoji: "👕" },
  { name: "6-9mo clothes", category: "Kids - Clothing", ageRange: "6-9mo", emoji: "👕" },
  { name: "9-12mo clothes", category: "Kids - Clothing", ageRange: "9-12mo", emoji: "👕" },
  { name: "12-18mo clothes", category: "Kids - Clothing", ageRange: "12-18mo", emoji: "👕" },
  { name: "18-24mo clothes", category: "Kids - Clothing", ageRange: "18-24mo", emoji: "👕" },
  { name: "2T clothes", category: "Kids - Clothing", ageRange: "2T", emoji: "👕" },
  { name: "3T clothes", category: "Kids - Clothing", ageRange: "3T", emoji: "👕" },
  { name: "4T clothes", category: "Kids - Clothing", ageRange: "4T", emoji: "👕" },
  { name: "5T clothes", category: "Kids - Clothing", ageRange: "5T", emoji: "👕" },
  { name: "Winter jacket", category: "Kids - Clothing", ageRange: "", emoji: "👕" },
  { name: "Rain jacket", category: "Kids - Clothing", ageRange: "", emoji: "👕" },
  { name: "Snow suit", category: "Kids - Clothing", ageRange: "", emoji: "👕" },
  { name: "Swimsuit", category: "Kids - Clothing", ageRange: "", emoji: "👕" },
  { name: "Halloween costume", category: "Kids - Clothing", ageRange: "", emoji: "👕" },
  { name: "Shoes (infant)", category: "Kids - Clothing", ageRange: "0-12mo", emoji: "👕" },
  { name: "Shoes (toddler)", category: "Kids - Clothing", ageRange: "12-36mo", emoji: "👕" },
  { name: "Rain boots", category: "Kids - Clothing", ageRange: "", emoji: "👕" },
  { name: "Snow boots", category: "Kids - Clothing", ageRange: "", emoji: "👕" },
  { name: "Sandals", category: "Kids - Clothing", ageRange: "", emoji: "👕" },
  { name: "Mittens", category: "Kids - Clothing", ageRange: "", emoji: "👕" },
  { name: "Winter hat", category: "Kids - Clothing", ageRange: "", emoji: "👕" },
  { name: "Sun hat", category: "Kids - Clothing", ageRange: "", emoji: "👕" },

  // ── Kids - Gear ──────────────────────────────────────────────────
  { name: "Baby monitor", category: "Kids - Gear", ageRange: "0-24mo", emoji: "🎪" },
  { name: "White noise machine", category: "Kids - Gear", ageRange: "0-24mo", emoji: "🎪" },
  { name: "Bottle warmer", category: "Kids - Gear", ageRange: "0-12mo", emoji: "🎪" },
  { name: "Breast pump", category: "Kids - Gear", ageRange: "0-12mo", emoji: "🎪" },
  { name: "Nursing pillow", category: "Kids - Gear", ageRange: "0-12mo", emoji: "🎪" },
  { name: "Diaper bag", category: "Kids - Gear", ageRange: "0-36mo", emoji: "🎪" },
  { name: "Baby carrier (wrap)", category: "Kids - Gear", ageRange: "0-12mo", emoji: "🎪" },
  { name: "Baby carrier (structured)", category: "Kids - Gear", ageRange: "0-36mo", emoji: "🎪" },
  { name: "Infant car seat", category: "Kids - Gear", ageRange: "0-12mo", emoji: "🎪" },
  { name: "Convertible car seat", category: "Kids - Gear", ageRange: "0-48mo", emoji: "🎪" },
  { name: "Booster seat", category: "Kids - Gear", ageRange: "36-60mo", emoji: "🎪" },
  { name: "Stroller", category: "Kids - Gear", ageRange: "0-48mo", emoji: "🎪" },
  { name: "Double stroller", category: "Kids - Gear", ageRange: "0-48mo", emoji: "🎪" },
  { name: "Jogging stroller", category: "Kids - Gear", ageRange: "6-48mo", emoji: "🎪" },
  { name: "Baby gate", category: "Kids - Gear", ageRange: "6-36mo", emoji: "🎪" },
  { name: "Cabinet locks", category: "Kids - Gear", ageRange: "6-36mo", emoji: "🎪" },
  { name: "Outlet covers", category: "Kids - Gear", ageRange: "6-36mo", emoji: "🎪" },
  { name: "Bumbo seat", category: "Kids - Gear", ageRange: "3-12mo", emoji: "🎪" },
  { name: "Bouncer", category: "Kids - Gear", ageRange: "0-6mo", emoji: "🎪" },
  { name: "Swing", category: "Kids - Gear", ageRange: "0-6mo", emoji: "🎪" },
  { name: "Pack n play", category: "Kids - Gear", ageRange: "0-36mo", emoji: "🎪" },
  { name: "Travel crib", category: "Kids - Gear", ageRange: "0-36mo", emoji: "🎪" },
  { name: "Baby bathtub", category: "Kids - Gear", ageRange: "0-12mo", emoji: "🎪" },
  { name: "Potty seat", category: "Kids - Gear", ageRange: "18-48mo", emoji: "🎪" },
  { name: "Step stool", category: "Kids - Gear", ageRange: "12-60mo", emoji: "🎪" },
  { name: "Night light", category: "Kids - Gear", ageRange: "", emoji: "🎪" },
  { name: "Humidifier", category: "Kids - Gear", ageRange: "", emoji: "🎪" },
  { name: "Nail clippers", category: "Kids - Gear", ageRange: "0-12mo", emoji: "🎪" },
  { name: "Thermometer", category: "Kids - Gear", ageRange: "", emoji: "🎪" },
  { name: "Nasal aspirator", category: "Kids - Gear", ageRange: "0-24mo", emoji: "🎪" },
  { name: "Sound machine", category: "Kids - Gear", ageRange: "", emoji: "🎪" },
  { name: "Diaper pail", category: "Kids - Gear", ageRange: "0-36mo", emoji: "🎪" },
  { name: "Changing pad", category: "Kids - Gear", ageRange: "0-24mo", emoji: "🎪" },
  { name: "Bottle drying rack", category: "Kids - Gear", ageRange: "0-12mo", emoji: "🎪" },
  { name: "Baby food maker", category: "Kids - Gear", ageRange: "4-18mo", emoji: "🎪" },

  // ── Kids - Feeding ───────────────────────────────────────────────
  { name: "Bottles", category: "Kids - Feeding", ageRange: "0-12mo", emoji: "🍼" },
  { name: "Bottle set", category: "Kids - Feeding", ageRange: "0-12mo", emoji: "🍼" },
  { name: "Sippy cups", category: "Kids - Feeding", ageRange: "6-24mo", emoji: "🍼" },
  { name: "Straw cups", category: "Kids - Feeding", ageRange: "12-48mo", emoji: "🍼" },
  { name: "Plates (baby)", category: "Kids - Feeding", ageRange: "6-24mo", emoji: "🍼" },
  { name: "Bowls (baby)", category: "Kids - Feeding", ageRange: "6-24mo", emoji: "🍼" },
  { name: "Baby spoons", category: "Kids - Feeding", ageRange: "4-18mo", emoji: "🍼" },
  { name: "High chair", category: "Kids - Feeding", ageRange: "6-36mo", emoji: "🍼" },
  { name: "Booster seat (dining)", category: "Kids - Feeding", ageRange: "24-60mo", emoji: "🍼" },
  { name: "Bib set", category: "Kids - Feeding", ageRange: "0-24mo", emoji: "🍼" },
  { name: "Silicone bibs", category: "Kids - Feeding", ageRange: "6-36mo", emoji: "🍼" },
  { name: "Food pouches", category: "Kids - Feeding", ageRange: "6-24mo", emoji: "🍼" },
  { name: "Snack catcher", category: "Kids - Feeding", ageRange: "9-36mo", emoji: "🍼" },
  { name: "Breast milk storage bags", category: "Kids - Feeding", ageRange: "0-12mo", emoji: "🍼" },
  { name: "Formula dispenser", category: "Kids - Feeding", ageRange: "0-12mo", emoji: "🍼" },
  { name: "Nursing cover", category: "Kids - Feeding", ageRange: "0-12mo", emoji: "🍼" },
  { name: "Burp cloths", category: "Kids - Feeding", ageRange: "0-12mo", emoji: "🍼" },

  // ── Kids - Sleep ─────────────────────────────────────────────────
  { name: "Crib", category: "Kids - Sleep", ageRange: "0-36mo", emoji: "😴" },
  { name: "Bassinet", category: "Kids - Sleep", ageRange: "0-6mo", emoji: "😴" },
  { name: "Toddler bed", category: "Kids - Sleep", ageRange: "18-48mo", emoji: "😴" },
  { name: "Crib mattress", category: "Kids - Sleep", ageRange: "0-36mo", emoji: "😴" },
  { name: "Crib sheets", category: "Kids - Sleep", ageRange: "0-36mo", emoji: "😴" },
  { name: "Sleep sack", category: "Kids - Sleep", ageRange: "0-24mo", emoji: "😴" },
  { name: "Swaddle set", category: "Kids - Sleep", ageRange: "0-4mo", emoji: "😴" },
  { name: "Mobile", category: "Kids - Sleep", ageRange: "0-6mo", emoji: "😴" },
  { name: "Blackout curtains", category: "Kids - Sleep", ageRange: "", emoji: "😴" },
  { name: "Toddler pillow", category: "Kids - Sleep", ageRange: "18-48mo", emoji: "😴" },
  { name: "Twin bed frame", category: "Kids - Sleep", ageRange: "36-60mo", emoji: "😴" },
  { name: "Bed rail", category: "Kids - Sleep", ageRange: "24-60mo", emoji: "😴" },

  // ── Kids - Toys ──────────────────────────────────────────────────
  { name: "Play mat", category: "Kids - Toys", ageRange: "0-12mo", emoji: "🧸" },
  { name: "Activity gym", category: "Kids - Toys", ageRange: "0-6mo", emoji: "🧸" },
  { name: "Stacking rings", category: "Kids - Toys", ageRange: "6-18mo", emoji: "🧸" },
  { name: "Shape sorter", category: "Kids - Toys", ageRange: "12-36mo", emoji: "🧸" },
  { name: "Push walker", category: "Kids - Toys", ageRange: "9-18mo", emoji: "🧸" },
  { name: "Pull toys", category: "Kids - Toys", ageRange: "12-36mo", emoji: "🧸" },
  { name: "Building blocks", category: "Kids - Toys", ageRange: "12-48mo", emoji: "🧸" },
  { name: "Duplo set", category: "Kids - Toys", ageRange: "18-60mo", emoji: "🧸" },
  { name: "Lego set", category: "Kids - Toys", ageRange: "48-60mo", emoji: "🧸" },
  { name: "Play kitchen", category: "Kids - Toys", ageRange: "24-60mo", emoji: "🧸" },
  { name: "Tool bench", category: "Kids - Toys", ageRange: "24-60mo", emoji: "🧸" },
  { name: "Dollhouse", category: "Kids - Toys", ageRange: "36-60mo", emoji: "🧸" },
  { name: "Train set", category: "Kids - Toys", ageRange: "24-60mo", emoji: "🧸" },
  { name: "Puzzles (baby)", category: "Kids - Toys", ageRange: "12-24mo", emoji: "🧸" },
  { name: "Puzzles (toddler)", category: "Kids - Toys", ageRange: "24-48mo", emoji: "🧸" },
  { name: "Puzzles (kid)", category: "Kids - Toys", ageRange: "48-60mo", emoji: "🧸" },
  { name: "Ride-on toy", category: "Kids - Toys", ageRange: "12-36mo", emoji: "🧸" },
  { name: "Tricycle", category: "Kids - Toys", ageRange: "24-48mo", emoji: "🧸" },
  { name: "Balance bike", category: "Kids - Toys", ageRange: "24-60mo", emoji: "🧸" },
  { name: "Bicycle with training wheels", category: "Kids - Toys", ageRange: "36-60mo", emoji: "🧸" },
  { name: "Scooter", category: "Kids - Toys", ageRange: "36-60mo", emoji: "🧸" },
  { name: "Wagon", category: "Kids - Toys", ageRange: "12-60mo", emoji: "🧸" },
  { name: "Sandbox", category: "Kids - Toys", ageRange: "18-60mo", emoji: "🧸" },
  { name: "Swing set", category: "Kids - Toys", ageRange: "24-60mo", emoji: "🧸" },
  { name: "Slide", category: "Kids - Toys", ageRange: "18-60mo", emoji: "🧸" },
  { name: "Trampoline (toddler)", category: "Kids - Toys", ageRange: "24-60mo", emoji: "🧸" },
  { name: "Water table", category: "Kids - Toys", ageRange: "12-48mo", emoji: "🧸" },
  { name: "Play tent", category: "Kids - Toys", ageRange: "18-60mo", emoji: "🧸" },
  { name: "Stuffed animals", category: "Kids - Toys", ageRange: "", emoji: "🧸" },
  { name: "Baby dolls", category: "Kids - Toys", ageRange: "18-60mo", emoji: "🧸" },
  { name: "Action figures", category: "Kids - Toys", ageRange: "36-60mo", emoji: "🧸" },
  { name: "Play-Doh set", category: "Kids - Toys", ageRange: "24-60mo", emoji: "🧸" },
  { name: "Art easel", category: "Kids - Toys", ageRange: "24-60mo", emoji: "🧸" },
  { name: "Magna-Tiles", category: "Kids - Toys", ageRange: "36-60mo", emoji: "🧸" },
  { name: "Marble run", category: "Kids - Toys", ageRange: "36-60mo", emoji: "🧸" },

  // ── Kids - Books ─────────────────────────────────────────────────
  { name: "Board books set", category: "Kids - Books", ageRange: "0-24mo", emoji: "📚" },
  { name: "Touch-and-feel books", category: "Kids - Books", ageRange: "0-18mo", emoji: "📚" },
  { name: "First words books", category: "Kids - Books", ageRange: "6-24mo", emoji: "📚" },
  { name: "Picture books", category: "Kids - Books", ageRange: "12-60mo", emoji: "📚" },
  { name: "Chapter books", category: "Kids - Books", ageRange: "48-60mo", emoji: "📚" },
  { name: "Activity books", category: "Kids - Books", ageRange: "24-60mo", emoji: "📚" },
  { name: "Coloring books", category: "Kids - Books", ageRange: "24-60mo", emoji: "📚" },

  // ── Kids - Furniture ─────────────────────────────────────────────
  { name: "Changing table", category: "Kids - Furniture", ageRange: "0-24mo", emoji: "🛏️" },
  { name: "Dresser", category: "Kids - Furniture", ageRange: "", emoji: "🛏️" },
  { name: "Bookshelf (kids)", category: "Kids - Furniture", ageRange: "", emoji: "🛏️" },
  { name: "Toy chest", category: "Kids - Furniture", ageRange: "", emoji: "🛏️" },
  { name: "Kids table and chairs", category: "Kids - Furniture", ageRange: "24-60mo", emoji: "🛏️" },
  { name: "Rocking chair", category: "Kids - Furniture", ageRange: "", emoji: "🛏️" },
  { name: "Glider", category: "Kids - Furniture", ageRange: "", emoji: "🛏️" },
  { name: "Nursery rug", category: "Kids - Furniture", ageRange: "", emoji: "🛏️" },

  // ── Kids - Outdoor ───────────────────────────────────────────────
  { name: "Bike helmet", category: "Kids - Outdoor", ageRange: "12-60mo", emoji: "⛺" },
  { name: "Knee pads", category: "Kids - Outdoor", ageRange: "24-60mo", emoji: "⛺" },
  { name: "Life jacket", category: "Kids - Outdoor", ageRange: "6-60mo", emoji: "⛺" },
  { name: "Camping chair (kids)", category: "Kids - Outdoor", ageRange: "24-60mo", emoji: "⛺" },
  { name: "Sleeping bag (kids)", category: "Kids - Outdoor", ageRange: "36-60mo", emoji: "⛺" },
  { name: "Backpack carrier", category: "Kids - Outdoor", ageRange: "6-36mo", emoji: "⛺" },
  { name: "Beach toys", category: "Kids - Outdoor", ageRange: "12-60mo", emoji: "⛺" },
  { name: "Sled", category: "Kids - Outdoor", ageRange: "24-60mo", emoji: "⛺" },
  { name: "Ski gear", category: "Kids - Outdoor", ageRange: "36-60mo", emoji: "⛺" },

  // ── Household ────────────────────────────────────────────────────
  { name: "Coffee maker", category: "Household", ageRange: "", emoji: "🏠" },
  { name: "Toaster", category: "Household", ageRange: "", emoji: "🏠" },
  { name: "Blender", category: "Household", ageRange: "", emoji: "🏠" },
  { name: "Instant Pot", category: "Household", ageRange: "", emoji: "🏠" },
  { name: "Air fryer", category: "Household", ageRange: "", emoji: "🏠" },
  { name: "Stand mixer", category: "Household", ageRange: "", emoji: "🏠" },
  { name: "Food processor", category: "Household", ageRange: "", emoji: "🏠" },
  { name: "Vacuum", category: "Household", ageRange: "", emoji: "🏠" },
  { name: "Robot vacuum", category: "Household", ageRange: "", emoji: "🏠" },
  { name: "Iron", category: "Household", ageRange: "", emoji: "🏠" },
  { name: "Steamer", category: "Household", ageRange: "", emoji: "🏠" },
  { name: "Sewing machine", category: "Household", ageRange: "", emoji: "🏠" },
  { name: "Tool set", category: "Household", ageRange: "", emoji: "🏠" },
  { name: "Drill", category: "Household", ageRange: "", emoji: "🏠" },
  { name: "Ladder", category: "Household", ageRange: "", emoji: "🏠" },
  { name: "Storage bins", category: "Household", ageRange: "", emoji: "🏠" },
  { name: "Bookshelf", category: "Household", ageRange: "", emoji: "🏠" },
  { name: "Desk", category: "Household", ageRange: "", emoji: "🏠" },
  { name: "Office chair", category: "Household", ageRange: "", emoji: "🏠" },
  { name: "Lamp", category: "Household", ageRange: "", emoji: "🏠" },
  { name: "Fan", category: "Household", ageRange: "", emoji: "🏠" },
  { name: "Space heater", category: "Household", ageRange: "", emoji: "🏠" },
  { name: "Air purifier", category: "Household", ageRange: "", emoji: "🏠" },
  { name: "Dehumidifier", category: "Household", ageRange: "", emoji: "🏠" },

  // ── Outdoor ──────────────────────────────────────────────────────
  { name: "Tent", category: "Outdoor", ageRange: "", emoji: "⛺" },
  { name: "Camping stove", category: "Outdoor", ageRange: "", emoji: "⛺" },
  { name: "Cooler", category: "Outdoor", ageRange: "", emoji: "⛺" },
  { name: "Lawn mower", category: "Outdoor", ageRange: "", emoji: "⛺" },
  { name: "Snow blower", category: "Outdoor", ageRange: "", emoji: "⛺" },
  { name: "Grill", category: "Outdoor", ageRange: "", emoji: "⛺" },
  { name: "Patio furniture", category: "Outdoor", ageRange: "", emoji: "⛺" },
  { name: "Fire pit", category: "Outdoor", ageRange: "", emoji: "⛺" },
  { name: "Garden tools", category: "Outdoor", ageRange: "", emoji: "⛺" },
  { name: "Wheelbarrow", category: "Outdoor", ageRange: "", emoji: "⛺" },
  { name: "Pressure washer", category: "Outdoor", ageRange: "", emoji: "⛺" },
  { name: "Kayak", category: "Outdoor", ageRange: "", emoji: "⛺" },
  { name: "Surfboard", category: "Outdoor", ageRange: "", emoji: "⛺" },
  { name: "Ski equipment", category: "Outdoor", ageRange: "", emoji: "⛺" },
  { name: "Snowboard", category: "Outdoor", ageRange: "", emoji: "⛺" },
  { name: "Camping chairs", category: "Outdoor", ageRange: "", emoji: "⛺" },
  { name: "Bike rack", category: "Outdoor", ageRange: "", emoji: "⛺" },
  { name: "Roof rack", category: "Outdoor", ageRange: "", emoji: "⛺" },

  // ── Furniture ────────────────────────────────────────────────────
  { name: "Couch", category: "Furniture", ageRange: "", emoji: "🛋️" },
  { name: "Loveseat", category: "Furniture", ageRange: "", emoji: "🛋️" },
  { name: "Armchair", category: "Furniture", ageRange: "", emoji: "🛋️" },
  { name: "Coffee table", category: "Furniture", ageRange: "", emoji: "🛋️" },
  { name: "End table", category: "Furniture", ageRange: "", emoji: "🛋️" },
  { name: "Dining table", category: "Furniture", ageRange: "", emoji: "🛋️" },
  { name: "Dining chairs", category: "Furniture", ageRange: "", emoji: "🛋️" },
  { name: "Bar stools", category: "Furniture", ageRange: "", emoji: "🛋️" },
  { name: "Bed frame", category: "Furniture", ageRange: "", emoji: "🛋️" },
  { name: "Mattress", category: "Furniture", ageRange: "", emoji: "🛋️" },
  { name: "Nightstand", category: "Furniture", ageRange: "", emoji: "🛋️" },
  { name: "TV stand", category: "Furniture", ageRange: "", emoji: "🛋️" },
  { name: "Bookcase", category: "Furniture", ageRange: "", emoji: "🛋️" },
  { name: "Filing cabinet", category: "Furniture", ageRange: "", emoji: "🛋️" },
  { name: "Rug", category: "Furniture", ageRange: "", emoji: "🛋️" },
  { name: "Curtains", category: "Furniture", ageRange: "", emoji: "🛋️" },

  // ── Electronics ──────────────────────────────────────────────────
  { name: "TV", category: "Electronics", ageRange: "", emoji: "📱" },
  { name: "Monitor", category: "Electronics", ageRange: "", emoji: "📱" },
  { name: "Laptop", category: "Electronics", ageRange: "", emoji: "📱" },
  { name: "Tablet", category: "Electronics", ageRange: "", emoji: "📱" },
  { name: "Printer", category: "Electronics", ageRange: "", emoji: "📱" },
  { name: "Speaker", category: "Electronics", ageRange: "", emoji: "📱" },
  { name: "Headphones", category: "Electronics", ageRange: "", emoji: "📱" },
  { name: "Camera", category: "Electronics", ageRange: "", emoji: "📱" },
  { name: "Gaming console", category: "Electronics", ageRange: "", emoji: "📱" },
  { name: "Router", category: "Electronics", ageRange: "", emoji: "📱" },
  { name: "External hard drive", category: "Electronics", ageRange: "", emoji: "📱" },
  { name: "Keyboard", category: "Electronics", ageRange: "", emoji: "📱" },
  { name: "Mouse", category: "Electronics", ageRange: "", emoji: "📱" },
  { name: "Webcam", category: "Electronics", ageRange: "", emoji: "📱" },
  { name: "Projector", category: "Electronics", ageRange: "", emoji: "📱" },
];

export function searchProducts(query: string): Product[] {
  const q = query.toLowerCase().trim();
  if (q.length < 2) return [];
  return PRODUCTS.filter((p) => p.name.toLowerCase().includes(q)).slice(0, 10);
}

export function getProductsByCategory(category: string): Product[] {
  return PRODUCTS.filter((p) => p.category === category);
}
